2022-05-09 21:06:44,799 [ERROR] app: Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 393, in _resolve_name
    rval = d[token]
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 372, in _access_cls
    return self.fallback[key]
KeyError: 'Transactions'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\app\auth\__init__.py", line 24, in register
    user = User.query.filter_by(email=form.email.data).first()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1901, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3425, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3464, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1918, in _post_configure_properties
    prop.init()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 231, in init
    self.do_init()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2150, in do_init
    self._process_dependent_arguments()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2245, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2112, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "C:\Users\echio\Documents\School Stuff\NJIT\Classes\(9) Fourth Year - Spring 2022\IS 218-004 - Building Web Applications\my_stuff\final_flask_start\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->users, expression 'Transactions' failed to locate a name ('Transactions'). If this is a class name, consider adding this relationship() to the <class 'app.db.models.User'> class after both dependent classes have been defined.
